@startuml

start
:User start analysis;

:Retrieve alldata.xlsx file;

:Create publication nodes;

:Create network graph;

:Cluster publications and assign cluster names;

:Analyse cluster metrics;

:Save clusters in excel;

stop
@enduml