@startuml

start

while() is ([For all nodes])
    if() then ([interaction meets min_strength])
    : Add edges to node \n based on bibliographic coupling;
    : Add bibliographic couple to networkx graph;
    else 
    : Add orphan node to graph;
    endif

endwhile ([else])
:Apply clustering algorithm;

while() is ([For all clusters])
    if() then ([cluster size larger than 1])
    : Add cluster number to all publications in cluster;

    else
    : Add publications of clusters with only 1 publication to respective outlier dataframes;
    endif

endwhile([else])

:Save network file as an excel sheet;
:Save recent_outlier and outlier dataframes as excel;
:Return all cluster dataframes to Data Analysis;

stop

@enduml
